from collections.abc import Sequence

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models import JuryScore, JuryScoreChange
from app.schemas import JuryScoreCreate, JuryScoreUpdate


class JuryScoreRepository:
    """Data access layer for jury scores."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def list_scores_by_participant(
        self, participant_id: int, with_relations: bool = False
    ) -> Sequence[JuryScore]:
        """
        Retrieve all jury scores for a specific participant.

        Args:
            participant_id: ID of the participant
            with_relations: If True, eagerly load jury and participant relations

        Returns:
            List of JuryScore instances ordered by ID
        """
        stmt = select(JuryScore).where(JuryScore.participant_id == participant_id).order_by(JuryScore.id)

        if with_relations:
            stmt = stmt.options(selectinload(JuryScore.jury), selectinload(JuryScore.participant))

        result = await self._session.execute(stmt)
        return result.scalars().all()

    async def get_score_by_id(self, score_id: int, with_relations: bool = False) -> JuryScore | None:
        """
        Retrieve a jury score by ID.

        Args:
            score_id: ID of the jury score
            with_relations: If True, eagerly load related entities

        Returns:
            JuryScore instance or None if not found
        """
        stmt = select(JuryScore).where(JuryScore.id == score_id)

        if with_relations:
            stmt = stmt.options(
                selectinload(JuryScore.jury),
                selectinload(JuryScore.participant),
                selectinload(JuryScore.changes),
            )

        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_score_by_jury_and_participant(self, jury_id: int, participant_id: int) -> JuryScore | None:
        """
        Retrieve a jury score by jury and participant IDs.
        Used for uniqueness validation.

        Args:
            jury_id: ID of the jury member
            participant_id: ID of the participant

        Returns:
            JuryScore instance or None if not found
        """
        stmt = select(JuryScore).where(JuryScore.jury_id == jury_id, JuryScore.participant_id == participant_id)
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def create_score(self, data: JuryScoreCreate) -> JuryScore:
        """
        Create a new jury score.

        Args:
            data: Score creation data

        Returns:
            Created JuryScore instance
        """
        score = JuryScore(
            jury_id=data.jury_id,
            participant_id=data.participant_id,
            organization_score=data.organization_score,
            content=data.content,
            visuals=data.visuals,
            mechanics=data.mechanics,
            delivery=data.delivery,
            comment=data.comment,
        )
        self._session.add(score)
        await self._session.flush()
        await self._session.refresh(score)
        return score

    async def update_score(self, score: JuryScore, data: JuryScoreUpdate) -> JuryScore:
        """
        Update an existing jury score.

        Args:
            score: Existing JuryScore instance
            data: Update data with optional fields

        Returns:
            Updated JuryScore instance
        """
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(score, field, value)

        await self._session.flush()
        await self._session.refresh(score)
        return score

    async def delete_score(self, score: JuryScore) -> None:
        """
        Delete a jury score.

        Args:
            score: JuryScore instance to delete
        """
        await self._session.delete(score)
        await self._session.flush()

    async def create_score_change(self, jury_score_id: int, jury_id: int) -> JuryScoreChange:
        """
        Create an audit trail entry for score update.

        Args:
            jury_score_id: ID of the updated score
            jury_id: ID of the jury member who made the change

        Returns:
            Created JuryScoreChange instance
        """
        change = JuryScoreChange(
            jury_scores_id=jury_score_id,
            jury_id=jury_id,
            # update_time is auto-generated by server_default
        )
        self._session.add(change)
        await self._session.flush()
        await self._session.refresh(change)
        return change
