openapi: 3.0.0
info:
  title: Topics and Draw results API
  version: 1.0.0
  description: >
    API для управления темами мероприятий и проведения жеребьёвки.
    Включает CRUD тем, запуск жеребьёвки и получение её результатов.

servers:
  - url: /api/v1
    description: Базовый путь API

tags:
  - name: Topics
    description: Управление темами мероприятий
  - name: Draw
    description: Запуск жеребьёвки тем
  - name: DrawResults
    description: Получение результатов жеребьёвки

paths:
  /topics:
    get:
      tags: [Topics]
      summary: Получить список тем для секции
      parameters:
        - in: query
          name: sectionId
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: Список тем
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Topic"

    post:
      tags: [Topics]
      summary: Создать новую тему для секции
      parameters:
        - in: query
          name: sectionId
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TopicCreate"
      responses:
        201:
          description: Тема создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
        400:
          description: Некорректные данные
        404:
          description: Секция не найдена

  /topics/{topicId}:
    get:
      tags: [Topics]
      summary: Получить тему по ID
      parameters:
        - in: path
          name: topicId
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: Тема найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
        404:
          description: Тема не найдена

    put:
      tags: [Topics]
      summary: Обновить тему
      parameters:
        - in: path
          name: topicId
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TopicUpdate"
      responses:
        200:
          description: Тема обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topic"
        400:
          description: Некорректные данные
        409:
          description: Тема уже назначена группе
        404:
          description: Тема не найдена

    delete:
      tags: [Topics]
      summary: Удалить тему
      parameters:
        - in: path
          name: topicId
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        204:
          description: Тема удалена
        409:
          description: Тема уже назначена группе
        404:
          description: Тема не найдена

  /draw/run:
    post:
      tags: [Draw]
      summary: Запустить жеребьёвку для секции
      parameters:
        - in: query
          name: sectionId
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: Жеребьёвка выполнена
        404:
          description: Секция не найдена
        409:
          description: Недостаточно групп или тем

  /draw-results:
    get:
      tags: [DrawResults]
      summary: Получить результаты жеребьёвки
      parameters:
        - in: query
          name: sectionId
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: Результаты жеребьёвки
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DrawResult"
        404:
          description: Секция не найдена

components:
  schemas:
    Topic:
      type: object
      required: [id, section_id, name]
      properties:
        id:
          type: integer
          minimum: 1
        section_id:
          type: integer
          minimum: 1
        name:
          type: string
          minLength: 3
          maxLength: 50

    TopicCreate:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 50

    TopicUpdate:
      type: object
      description: Данные для обновления темы
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 50
        section_id:
          type: integer
          minimum: 1

    DrawResult:
      type: object
      required: [group_id, group_name, topics]
      properties:
        group_id:
          type: integer
          minimum: 1
        group_name:
          type: string
        topics:
          type: array
          items:
            type: object
            required: [topic_id, topic_name]
            properties:
              topic_id:
                type: integer
                minimum: 1
              topic_name:
                type: string
                minLength: 3
                maxLength: 50
