openapi: 3.0.3
info:
  title: Цифровой Управляющий Мероприятиями - Draw Notifications API
  description: API для отправки уведомлений о результатах жеребьевки
  version: 1.0.0

servers:
  - url: /api/v1
    description: Server

tags:
  - name: Draw
    description: Уведомления о жеребьевке

paths:
  /notifications/draw/results:
    post:
      tags:
        - Draw
      summary: Отправить результаты жеребьевки группе
      description: |
        Отправляет уведомление на email всех участников группы и руководителю с назначенной темой
        и техническими требованиями.
        Тема письма: [Название мероприятия + год проведения] [Название группы] - Результаты жеребьевки
      operationId: sendDrawResultsNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DrawResultsNotificationRequest'
      responses:
        '200':
          description: Уведомление о результатах жеребьевки отправлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ошибка при отправке
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    DrawResultsNotificationRequest:
      type: object
      required:
        - eventName
        - eventYear
        - groupName
        - assignedTopic
        - technicalRequirements
        - participantEmails
      properties:
        eventName:
          type: string
          description: Название мероприятия
          example: "Плакаты 1"
        eventYear:
          type: integer
          description: Год проведения
          example: 2024
        groupName:
          type: string
          description: Название группы
          example: "Группа А"
        assignedTopic:
          type: string
          description: Назначенная тема
          example: "Экологические проблемы современности"
        technicalRequirements:
          type: string
          description: Технические требования к оформлению работы
          example: "Формат A1, содержание плакатов..."
        participantEmails:
          type: array
          items:
            type: string
            format: email
          description: Email всех участников группы
          example: ["student1@example.com", "student2@example.com"]
        supervisorEmail:
          type: string
          format: email
          description: Email руководителя группы
          example: "supervisor@example.com"

    NotificationResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Успешность операции
        message:
          type: string
          description: Сообщение о результате
        deliveryStatus:
          type: object
          properties:
            email:
              type: array
              description: Статусы отправки email
              items:
                type: object
                properties:
                  recipient:
                    type: string
                  status:
                    type: string
                    enum: [SENT, FAILED]
                  error:
                    type: string
                    description: Описание ошибки (если status=FAILED)

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Код ошибки
        message:
          type: string
          description: Описание ошибки
        details:
          type: object
          description: Дополнительная информация об ошибке
